### ISSUE TITLE
Can this package be used for models with MongoDB connection?

### ISSUE THREAD

**Issue by mrlinnth** [laravel-json-api/laravel#142] opened 2021-12-10 17:57 UTC
I am using MongoDB and [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) package.
Will it is an issue since my models are using Jenssegers\Mongodb\Eloquent\Model instead of Laravel's Eloquent Model?

**Comment by lindyhopchris** [comment] 2021-12-10 18:40
That `Model` class extends the Laravel Eloquent `Model` class, so that shouldn't present any problems.

Tbh, the answer to this is: you'll need to give it a go and see. If anything doesn't work, I wouldn't support it out of the box in the `laravel-json-api/eloquent` package (that's the one that does the Eloquent integration) as it's designed for use with Laravel's implementation. If you give it a go with Mongodb and it doesn't work, then someone would need to ship an equivalent of `laravel-json-api/eloquent` that works with the Mongodb package.

I'm going to close this issue because I've answered the question. It would be good to hear how you get on, so feel free to comment on this issue to let me know what you come up with!

**Closed by lindyhopchris** 2021-12-10 18:40 UTC

**Comment by mrlinnth** [comment] 2021-12-11 12:26
@lindyhopchris 

Hey Chris, thanks for the prompt response.
I tested the example application with Jenssegers's Eloquent Model.

It WORKS! haha Should have tested before asking.

![image](https://user-images.githubusercontent.com/4952597/145676152-c0baea64-5a53-4263-bcc8-4e007fb13780.png)

There is few issues when testing filter function but that's because Mongo uses ObjectID instead of integer for id.
I am sure there is a way to fix it. Your documentation is really thorough and easy to follow.

Thank you so much for this amazing package.

I got assigned to migrate and restructure an old and messy API backend project.
I am looking for a package which 

- [x] has proper standards & convention
- [x] will boost the development time 
- [x] plays well with Laravel
- [x] easy to use
- [x] can be customized

Your package checked all points from what I have read and tested so far.

Awesome work :)

**Comment by lindyhopchris** [comment] 2021-12-11 12:44
Ah that's great news, really glad it works. Yeah you might have to ship your own filters, but that's easy to do as they are all essentially just implementing interfaces.

Thanks, really glad to hear you're finding the package useful!

**Comment by joshuahiwat** [comment] 2022-10-14 10:14
MongoDB doesn't work. The issue is that it can't find the attributes.
