### ISSUE TITLE
Problem with php 8.1 and readonly

### ISSUE THREAD

**Issue by xfchris** [laravel-json-api/laravel#156] opened 2022-01-14 07:54 UTC
Hello, I updated the version of php and it throws me this problem, how can I solve it?

![image](https://user-images.githubusercontent.com/1672860/149471276-860e938a-21da-48dd-bf38-620141ee2f1e.png)

**Comment by X-Coder264** [comment] 2022-01-14 09:45
`readonly` is a PHP 8.1 feature which the package does not support yet.

https://github.com/laravel-json-api/laravel/issues/138

**Comment by lindyhopchris** [comment] 2022-01-14 12:58
Yes, this is a duplicate of a previous issue. See #138 for PHP 8.1 - I'll add some instructions there as to how to install the dev version if you need to. I'm just waiting for Laravel 9 before I tag a major release. That's due in the next week or two.

**Closed by lindyhopchris** 2022-01-14 12:58 UTC
