### ISSUE TITLE
Unable to encode compound document. See previous exception for cause of failure.

### ISSUE THREAD

**Issue by Pok09** [laravel-json-api/laravel#263] opened 2023-11-07 04:40 UTC
I want to use it with [orchid.software](https://orchid.software)

I configured everything correctly,  but can't get it to work properly

`Unable to encode compound document. See previous exception for cause of ![01](https://github.com/laravel-json-api/laravel/assets/24459601/cd502404-1a67-4944-9282-de11da0da8e8)

**Comment by Pok09** [comment] 2023-11-07 08:08
The same error on a fresh installation of laravel

**Comment by lindyhopchris** [comment] 2023-11-07 09:04
> See previous exception for cause of failure

In your logs, there will be the previous exception which is the cause of the failure. What does that say?

**Comment by lindyhopchris** [comment] 2023-11-07 20:28
Closing this - you need to refer to the previous exception for the cause of the failure. That'll be in your logs.

FYI the next version of this package - v3.2 - will remove the catching of the original exception and just let that bubble up, rather than the cause being in the previous exception.

**Closed by lindyhopchris** 2023-11-07 20:28 UTC

**Comment by lindyhopchris** [comment] 2023-11-08 16:26
@veneliniliev are you using our controller action, or have you written your own controller action?

**Comment by veneliniliev** [comment] 2023-11-08 16:28
> @veneliniliev are you using our controller action, or have you written your own controller action?

i use `LaravelJsonApi\Laravel\Http\Controllers\JsonApiController`

**Comment by lindyhopchris** [comment] 2023-11-08 16:49
And the error is originating from something that is returned from that controller by the package's code, and not your own?

If so, can you create a separate issue as it is unrelated to this issue.
